---
abstract: 'A collection of scripts using Marpa::R2'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: '0.94'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MarpaX-Demo-SampleScripts
provides:
  MarpaX::Demo::SampleScripts:
    file: lib/MarpaX/Demo/SampleScripts.pm
    version: '1.03'
requires:
  Capture::Tiny: '0.25'
  Data::Dumper: '2.145'
  Data::Section: '0.200006'
  File::Slurp: '9999.19'
  Marpa::R2: '2.098'
  Marpa::R2::HTML: '2.098'
  Moo: '1.006001'
  POSIX: '1.32'
  Try::Tiny: '0.22'
  Types::Standard: '1.000004'
  charnames: '0'
  diagnostics: '0'
  open: '0'
  perl: '5.01'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/ronsavage/MarpaX-Demo-SampleScripts
version: '1.03'
